# Generated by Django 2.2.1 on 2019-05-22 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='bio',
            field=models.CharField(default='', max_length=500, verbose_name='Bio'),
        ),
    ]
