#define IDENTIFIER 0
#define CONSTANT 1
#define INT 2
#define BOOL 3
#define READ 4
#define WRITE 5
#define IF 6
#define ELSE 7
#define WHILE 8
#define MAIN 9
#define SEMICOLON 10
#define ARRAY 11
#define LEFTBRACKET 12
#define RIGHTBRAKET 13
#define LEFTSQUAREBRACKET 14
#define RIGHTSQUAREBRACKET 15
#define LEFTPARANTHESIS 16
#define RIGHTPARANTHESIS 17
#define PLUS 18
#define MINUS 19
#define MULTIPLY 20
#define DEVIDE 21
#define GREATER 22
#define SMALLER 23
#define GREATEREQUAL 24
#define SMALLEREQUAL 25
#define EQUAL 26
#define DIFFERENT 27
#define ASSIGNMENT 28
#define TRUE 29
#define FALSE 30

